### PR TITLE
Support agent forwarding in SSH

### PR DESCRIPTION
**Pull request by adammathys**

### CODE REVIEW

**Comment by forkata** [comment]
:+1:

**Comment by Senjai** [comment]
:shipit:

**Comment by alexblackie** [comment]
Woo :+1:

**Comment by bbuchalter** [comment]
Is this only relevant if don't have agent forwarding to all hosts?

**Comment by adammathys** [comment]
@bbuchalter Yes, this allows you to selectively forward when connecting. 

As an aside, you probably shouldn't turn agent forwarding on for all hosts. :wink:

**Pull request merged**
